~:
  .cmds:
    argparse.bash: https://github.com/nhoffman/argparse-bash.git?path=argparse.bash
    aliases.bash: https://github.com/ArturoRoberti/gurk_example_plugin/templates/aliases.bash
    add_licenses.bash: https://github.com/ArturoRoberti/gurk_example_plugin/templates/add_licenses.bash
  git: null
  Documents:
    Personal:
      CVs: null
      IDs: null
    General: null
    Work: null
